[package]
name = "custom-codegen"
version = "0.1.0"
edition = "2021"

[features]
xml = ["opcua/xml"]
json = ["serde_json", "serde", "serde_with", "opcua/json"]

default = ["xml", "json"]

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
log = { workspace = true }
serde_json = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true }

[dependencies.opcua]
path = "../../lib"
version = "0.13.0" # OPCUARustVersion
features = ["client", "console-logging"]
