[workspace]
resolver = "2"
members = [
    "lib",
    "samples/demo-server",
    "samples/simple-client",
    "samples/mqtt-client",
    "samples/simple-server",
    "samples/chess-server",
    "samples/discovery-client",
    "samples/event-client",
    "tools/certificate-creator",
    "samples/async-server",
    "opcua-codegen",
    "opcua-xml",
    "opcua-types"
]

[workspace.dependencies]
bitflags = "2.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
log = "0.4"
regex = "1.7"
lazy_static = "1.4.0"
uuid = { version = "1.2", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
byteorder = "1.4"
base64 = "0.21"
