extra_header: |
  // OPCUA for Rust
  // SPDX-License-Identifier: MPL-2.0
  // Copyright (C) 2017-2024 Adam Lock, Einar Omang
opcua_crate_path: crate
targets:
  - type: types
    file_path: tools/schema/schemas/1.0.4/Opc.Ua.Types.bsd
    output_dir: opcua-types/src/service_types
    enums_single_file: true
    opcua_types_path: crate
    default_excluded:
      - AnonymousIdentityToken
  - type: nodes
    file_path: tools/schema/schemas/1.0.4/Opc.Ua.NodeSet2.xml
    output_dir: lib/src/server/address_space/generated
    max_nodes_per_file: 100
    types:
      - file_path: tools/schema/schemas/1.0.4/Opc.Ua.Types.xsd
        root_path: crate::types
    own_namespaces:
      - "http://opcfoundation.org/UA/"
    imported_namespaces: []
    name: CoreNamespace
