// This file was autogenerated from schemas/1.0.4/Opc.Ua.Types.bsd by opcua-codegen
//
// DO NOT EDIT THIS FILE

// OPCUA for Rust
// SPDX-License-Identifier: MPL-2.0
// Copyright (C) 2017-2024 Adam Lock, Einar Omang
#[allow(unused)]
mod opcua {
    pub use crate as types;
}
pub mod enums;
pub use enums::*;
pub mod activate_session_request;
pub use activate_session_request::*;
pub mod activate_session_response;
pub use activate_session_response::*;
pub mod additional_parameters_type;
pub use additional_parameters_type::*;
pub mod add_nodes_item;
pub use add_nodes_item::*;
pub mod add_nodes_request;
pub use add_nodes_request::*;
pub mod add_nodes_response;
pub use add_nodes_response::*;
pub mod add_nodes_result;
pub use add_nodes_result::*;
pub mod add_references_item;
pub use add_references_item::*;
pub mod add_references_request;
pub use add_references_request::*;
pub mod add_references_response;
pub use add_references_response::*;
pub mod aggregate_configuration;
pub use aggregate_configuration::*;
pub mod aggregate_filter;
pub use aggregate_filter::*;
pub mod aggregate_filter_result;
pub use aggregate_filter_result::*;
pub mod alias_name_data_type;
pub use alias_name_data_type::*;
pub mod annotation;
pub use annotation::*;
pub mod anonymous_identity_token;
pub use anonymous_identity_token::*;
pub mod application_description;
pub use application_description::*;
pub mod argument;
pub use argument::*;
pub mod attribute_operand;
pub use attribute_operand::*;
pub mod axis_information;
pub use axis_information::*;
pub mod broker_connection_transport_data_type;
pub use broker_connection_transport_data_type::*;
pub mod broker_data_set_reader_transport_data_type;
pub use broker_data_set_reader_transport_data_type::*;
pub mod broker_data_set_writer_transport_data_type;
pub use broker_data_set_writer_transport_data_type::*;
pub mod broker_writer_group_transport_data_type;
pub use broker_writer_group_transport_data_type::*;
pub mod browse_description;
pub use browse_description::*;
pub mod browse_next_request;
pub use browse_next_request::*;
pub mod browse_next_response;
pub use browse_next_response::*;
pub mod browse_path;
pub use browse_path::*;
pub mod browse_path_result;
pub use browse_path_result::*;
pub mod browse_path_target;
pub use browse_path_target::*;
pub mod browse_request;
pub use browse_request::*;
pub mod browse_response;
pub use browse_response::*;
pub mod browse_result;
pub use browse_result::*;
pub mod build_info;
pub use build_info::*;
pub mod call_method_request;
pub use call_method_request::*;
pub mod call_method_result;
pub use call_method_result::*;
pub mod call_request;
pub use call_request::*;
pub mod call_response;
pub use call_response::*;
pub mod cancel_request;
pub use cancel_request::*;
pub mod cancel_response;
pub use cancel_response::*;
pub mod cartesian_coordinates;
pub use cartesian_coordinates::*;
pub mod channel_security_token;
pub use channel_security_token::*;
pub mod close_secure_channel_request;
pub use close_secure_channel_request::*;
pub mod close_secure_channel_response;
pub use close_secure_channel_response::*;
pub mod close_session_request;
pub use close_session_request::*;
pub mod close_session_response;
pub use close_session_response::*;
pub mod complex_number_type;
pub use complex_number_type::*;
pub mod configuration_version_data_type;
pub use configuration_version_data_type::*;
pub mod connection_transport_data_type;
pub use connection_transport_data_type::*;
pub mod content_filter;
pub use content_filter::*;
pub mod content_filter_element;
pub use content_filter_element::*;
pub mod content_filter_element_result;
pub use content_filter_element_result::*;
pub mod content_filter_result;
pub use content_filter_result::*;
pub mod create_monitored_items_request;
pub use create_monitored_items_request::*;
pub mod create_monitored_items_response;
pub use create_monitored_items_response::*;
pub mod create_session_request;
pub use create_session_request::*;
pub mod create_session_response;
pub use create_session_response::*;
pub mod create_subscription_request;
pub use create_subscription_request::*;
pub mod create_subscription_response;
pub use create_subscription_response::*;
pub mod currency_unit_type;
pub use currency_unit_type::*;
pub mod data_change_filter;
pub use data_change_filter::*;
pub mod data_change_notification;
pub use data_change_notification::*;
pub mod datagram_connection_transport_data_type;
pub use datagram_connection_transport_data_type::*;
pub mod datagram_writer_group_transport_data_type;
pub use datagram_writer_group_transport_data_type::*;
pub mod data_set_meta_data_type;
pub use data_set_meta_data_type::*;
pub mod data_set_reader_data_type;
pub use data_set_reader_data_type::*;
pub mod data_set_reader_message_data_type;
pub use data_set_reader_message_data_type::*;
pub mod data_set_reader_transport_data_type;
pub use data_set_reader_transport_data_type::*;
pub mod data_set_writer_data_type;
pub use data_set_writer_data_type::*;
pub mod data_set_writer_message_data_type;
pub use data_set_writer_message_data_type::*;
pub mod data_set_writer_transport_data_type;
pub use data_set_writer_transport_data_type::*;
pub mod data_type_attributes;
pub use data_type_attributes::*;
pub mod data_type_description;
pub use data_type_description::*;
pub mod data_type_schema_header;
pub use data_type_schema_header::*;
pub mod decimal_data_type;
pub use decimal_data_type::*;
pub mod delete_at_time_details;
pub use delete_at_time_details::*;
pub mod delete_event_details;
pub use delete_event_details::*;
pub mod delete_monitored_items_request;
pub use delete_monitored_items_request::*;
pub mod delete_monitored_items_response;
pub use delete_monitored_items_response::*;
pub mod delete_nodes_item;
pub use delete_nodes_item::*;
pub mod delete_nodes_request;
pub use delete_nodes_request::*;
pub mod delete_nodes_response;
pub use delete_nodes_response::*;
pub mod delete_raw_modified_details;
pub use delete_raw_modified_details::*;
pub mod delete_references_item;
pub use delete_references_item::*;
pub mod delete_references_request;
pub use delete_references_request::*;
pub mod delete_references_response;
pub use delete_references_response::*;
pub mod delete_subscriptions_request;
pub use delete_subscriptions_request::*;
pub mod delete_subscriptions_response;
pub use delete_subscriptions_response::*;
pub mod discovery_configuration;
pub use discovery_configuration::*;
pub mod double_complex_number_type;
pub use double_complex_number_type::*;
pub mod element_operand;
pub use element_operand::*;
pub mod endpoint_configuration;
pub use endpoint_configuration::*;
pub mod endpoint_description;
pub use endpoint_description::*;
pub mod endpoint_type;
pub use endpoint_type::*;
pub mod endpoint_url_list_data_type;
pub use endpoint_url_list_data_type::*;
pub mod enum_definition;
pub use enum_definition::*;
pub mod enum_description;
pub use enum_description::*;
pub mod enum_field;
pub use enum_field::*;
pub mod enum_value_type;
pub use enum_value_type::*;
pub mod ephemeral_key_type;
pub use ephemeral_key_type::*;
pub mod eu_information;
pub use eu_information::*;
pub mod event_field_list;
pub use event_field_list::*;
pub mod event_filter;
pub use event_filter::*;
pub mod event_filter_result;
pub use event_filter_result::*;
pub mod event_notification_list;
pub use event_notification_list::*;
pub mod field_meta_data;
pub use field_meta_data::*;
pub mod field_target_data_type;
pub use field_target_data_type::*;
pub mod filter_operand;
pub use filter_operand::*;
pub mod find_servers_on_network_request;
pub use find_servers_on_network_request::*;
pub mod find_servers_on_network_response;
pub use find_servers_on_network_response::*;
pub mod find_servers_request;
pub use find_servers_request::*;
pub mod find_servers_response;
pub use find_servers_response::*;
pub mod frame;
pub use frame::*;
pub mod generic_attributes;
pub use generic_attributes::*;
pub mod generic_attribute_value;
pub use generic_attribute_value::*;
pub mod get_endpoints_request;
pub use get_endpoints_request::*;
pub mod get_endpoints_response;
pub use get_endpoints_response::*;
pub mod history_data;
pub use history_data::*;
pub mod history_event;
pub use history_event::*;
pub mod history_event_field_list;
pub use history_event_field_list::*;
pub mod history_modified_data;
pub use history_modified_data::*;
pub mod history_read_details;
pub use history_read_details::*;
pub mod history_read_request;
pub use history_read_request::*;
pub mod history_read_response;
pub use history_read_response::*;
pub mod history_read_result;
pub use history_read_result::*;
pub mod history_read_value_id;
pub use history_read_value_id::*;
pub mod history_update_details;
pub use history_update_details::*;
pub mod history_update_request;
pub use history_update_request::*;
pub mod history_update_response;
pub use history_update_response::*;
pub mod history_update_result;
pub use history_update_result::*;
pub mod identity_mapping_rule_type;
pub use identity_mapping_rule_type::*;
pub mod issued_identity_token;
pub use issued_identity_token::*;
pub mod json_data_set_reader_message_data_type;
pub use json_data_set_reader_message_data_type::*;
pub mod json_data_set_writer_message_data_type;
pub use json_data_set_writer_message_data_type::*;
pub mod json_writer_group_message_data_type;
pub use json_writer_group_message_data_type::*;
pub mod key_value_pair;
pub use key_value_pair::*;
pub mod literal_operand;
pub use literal_operand::*;
pub mod mdns_discovery_configuration;
pub use mdns_discovery_configuration::*;
pub mod method_attributes;
pub use method_attributes::*;
pub mod model_change_structure_data_type;
pub use model_change_structure_data_type::*;
pub mod modification_info;
pub use modification_info::*;
pub mod modify_monitored_items_request;
pub use modify_monitored_items_request::*;
pub mod modify_monitored_items_response;
pub use modify_monitored_items_response::*;
pub mod modify_subscription_request;
pub use modify_subscription_request::*;
pub mod modify_subscription_response;
pub use modify_subscription_response::*;
pub mod monitored_item_create_request;
pub use monitored_item_create_request::*;
pub mod monitored_item_create_result;
pub use monitored_item_create_result::*;
pub mod monitored_item_modify_request;
pub use monitored_item_modify_request::*;
pub mod monitored_item_modify_result;
pub use monitored_item_modify_result::*;
pub mod monitored_item_notification;
pub use monitored_item_notification::*;
pub mod monitoring_filter;
pub use monitoring_filter::*;
pub mod monitoring_filter_result;
pub use monitoring_filter_result::*;
pub mod monitoring_parameters;
pub use monitoring_parameters::*;
pub mod network_address_data_type;
pub use network_address_data_type::*;
pub mod network_address_url_data_type;
pub use network_address_url_data_type::*;
pub mod network_group_data_type;
pub use network_group_data_type::*;
pub mod node_attributes;
pub use node_attributes::*;
pub mod node_reference;
pub use node_reference::*;
pub mod node_type_description;
pub use node_type_description::*;
pub mod notification_data;
pub use notification_data::*;
pub mod notification_message;
pub use notification_message::*;
pub mod object_attributes;
pub use object_attributes::*;
pub mod object_type_attributes;
pub use object_type_attributes::*;
pub mod open_secure_channel_request;
pub use open_secure_channel_request::*;
pub mod open_secure_channel_response;
pub use open_secure_channel_response::*;
pub mod option_set;
pub use option_set::*;
pub mod orientation;
pub use orientation::*;
pub mod parsing_result;
pub use parsing_result::*;
pub mod program_diagnostic_2_data_type;
pub use program_diagnostic_2_data_type::*;
pub mod program_diagnostic_data_type;
pub use program_diagnostic_data_type::*;
pub mod published_data_items_data_type;
pub use published_data_items_data_type::*;
pub mod published_data_set_data_type;
pub use published_data_set_data_type::*;
pub mod published_data_set_source_data_type;
pub use published_data_set_source_data_type::*;
pub mod published_events_data_type;
pub use published_events_data_type::*;
pub mod published_variable_data_type;
pub use published_variable_data_type::*;
pub mod publish_request;
pub use publish_request::*;
pub mod publish_response;
pub use publish_response::*;
pub mod pub_sub_configuration_data_type;
pub use pub_sub_configuration_data_type::*;
pub mod pub_sub_connection_data_type;
pub use pub_sub_connection_data_type::*;
pub mod pub_sub_group_data_type;
pub use pub_sub_group_data_type::*;
pub mod query_data_description;
pub use query_data_description::*;
pub mod query_data_set;
pub use query_data_set::*;
pub mod query_first_request;
pub use query_first_request::*;
pub mod query_first_response;
pub use query_first_response::*;
pub mod query_next_request;
pub use query_next_request::*;
pub mod query_next_response;
pub use query_next_response::*;
pub mod range;
pub use range::*;
pub mod rational_number;
pub use rational_number::*;
pub mod read_annotation_data_details;
pub use read_annotation_data_details::*;
pub mod read_at_time_details;
pub use read_at_time_details::*;
pub mod reader_group_data_type;
pub use reader_group_data_type::*;
pub mod reader_group_message_data_type;
pub use reader_group_message_data_type::*;
pub mod reader_group_transport_data_type;
pub use reader_group_transport_data_type::*;
pub mod read_event_details;
pub use read_event_details::*;
pub mod read_processed_details;
pub use read_processed_details::*;
pub mod read_raw_modified_details;
pub use read_raw_modified_details::*;
pub mod read_request;
pub use read_request::*;
pub mod read_response;
pub use read_response::*;
pub mod read_value_id;
pub use read_value_id::*;
pub mod redundant_server_data_type;
pub use redundant_server_data_type::*;
pub mod reference_description;
pub use reference_description::*;
pub mod reference_type_attributes;
pub use reference_type_attributes::*;
pub mod registered_server;
pub use registered_server::*;
pub mod register_nodes_request;
pub use register_nodes_request::*;
pub mod register_nodes_response;
pub use register_nodes_response::*;
pub mod register_server_2_request;
pub use register_server_2_request::*;
pub mod register_server_2_response;
pub use register_server_2_response::*;
pub mod register_server_request;
pub use register_server_request::*;
pub mod register_server_response;
pub use register_server_response::*;
pub mod relative_path;
pub use relative_path::*;
pub mod relative_path_element;
pub use relative_path_element::*;
pub mod republish_request;
pub use republish_request::*;
pub mod republish_response;
pub use republish_response::*;
pub mod role_permission_type;
pub use role_permission_type::*;
pub mod sampling_interval_diagnostics_data_type;
pub use sampling_interval_diagnostics_data_type::*;
pub mod semantic_change_structure_data_type;
pub use semantic_change_structure_data_type::*;
pub mod server_diagnostics_summary_data_type;
pub use server_diagnostics_summary_data_type::*;
pub mod server_on_network;
pub use server_on_network::*;
pub mod server_status_data_type;
pub use server_status_data_type::*;
pub mod service_counter_data_type;
pub use service_counter_data_type::*;
pub mod service_fault;
pub use service_fault::*;
pub mod session_diagnostics_data_type;
pub use session_diagnostics_data_type::*;
pub mod sessionless_invoke_request_type;
pub use sessionless_invoke_request_type::*;
pub mod sessionless_invoke_response_type;
pub use sessionless_invoke_response_type::*;
pub mod session_security_diagnostics_data_type;
pub use session_security_diagnostics_data_type::*;
pub mod set_monitoring_mode_request;
pub use set_monitoring_mode_request::*;
pub mod set_monitoring_mode_response;
pub use set_monitoring_mode_response::*;
pub mod set_publishing_mode_request;
pub use set_publishing_mode_request::*;
pub mod set_publishing_mode_response;
pub use set_publishing_mode_response::*;
pub mod set_triggering_request;
pub use set_triggering_request::*;
pub mod set_triggering_response;
pub use set_triggering_response::*;
pub mod signature_data;
pub use signature_data::*;
pub mod signed_software_certificate;
pub use signed_software_certificate::*;
pub mod simple_attribute_operand;
pub use simple_attribute_operand::*;
pub mod simple_type_description;
pub use simple_type_description::*;
pub mod status_change_notification;
pub use status_change_notification::*;
pub mod status_result;
pub use status_result::*;
pub mod structure_definition;
pub use structure_definition::*;
pub mod structure_description;
pub use structure_description::*;
pub mod structure_field;
pub use structure_field::*;
pub mod subscribed_data_set_data_type;
pub use subscribed_data_set_data_type::*;
pub mod subscribed_data_set_mirror_data_type;
pub use subscribed_data_set_mirror_data_type::*;
pub mod subscription_acknowledgement;
pub use subscription_acknowledgement::*;
pub mod subscription_diagnostics_data_type;
pub use subscription_diagnostics_data_type::*;
pub mod target_variables_data_type;
pub use target_variables_data_type::*;
pub mod three_d_cartesian_coordinates;
pub use three_d_cartesian_coordinates::*;
pub mod three_d_frame;
pub use three_d_frame::*;
pub mod three_d_orientation;
pub use three_d_orientation::*;
pub mod three_d_vector;
pub use three_d_vector::*;
pub mod time_zone_data_type;
pub use time_zone_data_type::*;
pub mod transfer_result;
pub use transfer_result::*;
pub mod transfer_subscriptions_request;
pub use transfer_subscriptions_request::*;
pub mod transfer_subscriptions_response;
pub use transfer_subscriptions_response::*;
pub mod translate_browse_paths_to_node_ids_request;
pub use translate_browse_paths_to_node_ids_request::*;
pub mod translate_browse_paths_to_node_ids_response;
pub use translate_browse_paths_to_node_ids_response::*;
pub mod trust_list_data_type;
pub use trust_list_data_type::*;
pub mod ua_binary_file_data_type;
pub use ua_binary_file_data_type::*;
pub mod uadp_data_set_reader_message_data_type;
pub use uadp_data_set_reader_message_data_type::*;
pub mod uadp_data_set_writer_message_data_type;
pub use uadp_data_set_writer_message_data_type::*;
pub mod uadp_writer_group_message_data_type;
pub use uadp_writer_group_message_data_type::*;
pub mod unregister_nodes_request;
pub use unregister_nodes_request::*;
pub mod unregister_nodes_response;
pub use unregister_nodes_response::*;
pub mod update_data_details;
pub use update_data_details::*;
pub mod update_event_details;
pub use update_event_details::*;
pub mod update_structure_data_details;
pub use update_structure_data_details::*;
pub mod user_identity_token;
pub use user_identity_token::*;
pub mod user_name_identity_token;
pub use user_name_identity_token::*;
pub mod user_token_policy;
pub use user_token_policy::*;
pub mod variable_attributes;
pub use variable_attributes::*;
pub mod variable_type_attributes;
pub use variable_type_attributes::*;
pub mod vector;
pub use vector::*;
pub mod view_attributes;
pub use view_attributes::*;
pub mod view_description;
pub use view_description::*;
pub mod write_request;
pub use write_request::*;
pub mod write_response;
pub use write_response::*;
pub mod writer_group_data_type;
pub use writer_group_data_type::*;
pub mod writer_group_message_data_type;
pub use writer_group_message_data_type::*;
pub mod writer_group_transport_data_type;
pub use writer_group_transport_data_type::*;
pub mod write_value;
pub use write_value::*;
pub mod x_509_identity_token;
pub use x_509_identity_token::*;
pub mod xv_type;
pub use xv_type::*;
#[cfg(feature = "xml")]
#[derive(Debug, Default, Copy, Clone)]
pub struct TypesXmlLoader;
#[cfg(feature = "xml")]
impl opcua::types::xml::XmlLoader for TypesXmlLoader {
    fn load_extension_object<'a>(
        &self,
        body: &opcua::types::xml::XmlElement,
        node_id: &opcua::types::NodeId,
        ctx: &opcua::types::xml::XmlContext<'a>,
    ) -> Option<Result<opcua::types::ExtensionObject, opcua::types::xml::FromXmlError>> {
        use opcua::types::xml::FromXml;
        let object_id = match node_id
            .as_object_id()
            .map_err(|_| "Invalid object ID".to_owned())
        {
            Ok(i) => i,
            Err(e) => return Some(Err(e.into())),
        };
        Some(
            match object_id {
                opcua::types::ObjectId::CallMethodRequest_Encoding_DefaultBinary => {
                    CallMethodRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EphemeralKeyType_Encoding_DefaultBinary => {
                    EphemeralKeyType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrokerWriterGroupTransportDataType_Encoding_DefaultBinary => {
                    BrokerWriterGroupTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UpdateEventDetails_Encoding_DefaultBinary => {
                    UpdateEventDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ContentFilterElement_Encoding_DefaultBinary => {
                    ContentFilterElement::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NetworkAddressUrlDataType_Encoding_DefaultBinary => {
                    NetworkAddressUrlDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MethodAttributes_Encoding_DefaultBinary => {
                    MethodAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TimeZoneDataType_Encoding_DefaultBinary => {
                    TimeZoneDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CloseSecureChannelRequest_Encoding_DefaultBinary => {
                    CloseSecureChannelRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataSetWriterTransportDataType_Encoding_DefaultBinary => {
                    DataSetWriterTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CancelRequest_Encoding_DefaultBinary => {
                    CancelRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RolePermissionType_Encoding_DefaultBinary => {
                    RolePermissionType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryModifiedData_Encoding_DefaultBinary => {
                    HistoryModifiedData::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AddNodesItem_Encoding_DefaultBinary => {
                    AddNodesItem::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::OpenSecureChannelResponse_Encoding_DefaultBinary => {
                    OpenSecureChannelResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TargetVariablesDataType_Encoding_DefaultBinary => {
                    TargetVariablesDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::WriteValue_Encoding_DefaultBinary => {
                    WriteValue::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DoubleComplexNumberType_Encoding_DefaultBinary => {
                    DoubleComplexNumberType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SemanticChangeStructureDataType_Encoding_DefaultBinary => {
                    SemanticChangeStructureDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UadpDataSetWriterMessageDataType_Encoding_DefaultBinary => {
                    UadpDataSetWriterMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::Vector_Encoding_DefaultBinary => {
                    Vector::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CloseSecureChannelResponse_Encoding_DefaultBinary => {
                    CloseSecureChannelResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadProcessedDetails_Encoding_DefaultBinary => {
                    ReadProcessedDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReferenceTypeAttributes_Encoding_DefaultBinary => {
                    ReferenceTypeAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TranslateBrowsePathsToNodeIdsRequest_Encoding_DefaultBinary => {
                    TranslateBrowsePathsToNodeIdsRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataSetWriterDataType_Encoding_DefaultBinary => {
                    DataSetWriterDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TransferSubscriptionsResponse_Encoding_DefaultBinary => {
                    TransferSubscriptionsResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EnumDescription_Encoding_DefaultBinary => {
                    EnumDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::FieldTargetDataType_Encoding_DefaultBinary => {
                    FieldTargetDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UadpDataSetReaderMessageDataType_Encoding_DefaultBinary => {
                    UadpDataSetReaderMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowsePath_Encoding_DefaultBinary => {
                    BrowsePath::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteRawModifiedDetails_Encoding_DefaultBinary => {
                    DeleteRawModifiedDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CallRequest_Encoding_DefaultBinary => {
                    CallRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrokerConnectionTransportDataType_Encoding_DefaultBinary => {
                    BrokerConnectionTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SetTriggeringResponse_Encoding_DefaultBinary => {
                    SetTriggeringResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteReferencesItem_Encoding_DefaultBinary => {
                    DeleteReferencesItem::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SignatureData_Encoding_DefaultBinary => {
                    SignatureData::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PublishedDataItemsDataType_Encoding_DefaultBinary => {
                    PublishedDataItemsDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ContentFilterResult_Encoding_DefaultBinary => {
                    ContentFilterResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ModelChangeStructureDataType_Encoding_DefaultBinary => {
                    ModelChangeStructureDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::WriterGroupDataType_Encoding_DefaultBinary => {
                    WriterGroupDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ServerDiagnosticsSummaryDataType_Encoding_DefaultBinary => {
                    ServerDiagnosticsSummaryDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SetPublishingModeRequest_Encoding_DefaultBinary => {
                    SetPublishingModeRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EventFieldList_Encoding_DefaultBinary => {
                    EventFieldList::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::QueryNextResponse_Encoding_DefaultBinary => {
                    QueryNextResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataSetWriterMessageDataType_Encoding_DefaultBinary => {
                    DataSetWriterMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ObjectAttributes_Encoding_DefaultBinary => {
                    ObjectAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteMonitoredItemsResponse_Encoding_DefaultBinary => {
                    DeleteMonitoredItemsResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::Range_Encoding_DefaultBinary => {
                    Range::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::GetEndpointsResponse_Encoding_DefaultBinary => {
                    GetEndpointsResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryUpdateDetails_Encoding_DefaultBinary => {
                    HistoryUpdateDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RepublishResponse_Encoding_DefaultBinary => {
                    RepublishResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TransferResult_Encoding_DefaultBinary => {
                    TransferResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::IssuedIdentityToken_Encoding_DefaultBinary => {
                    IssuedIdentityToken::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SimpleAttributeOperand_Encoding_DefaultBinary => {
                    SimpleAttributeOperand::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SetPublishingModeResponse_Encoding_DefaultBinary => {
                    SetPublishingModeResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadEventDetails_Encoding_DefaultBinary => {
                    ReadEventDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ContentFilterElementResult_Encoding_DefaultBinary => {
                    ContentFilterElementResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AnonymousIdentityToken_Encoding_DefaultBinary => {
                    AnonymousIdentityToken::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ChannelSecurityToken_Encoding_DefaultBinary => {
                    ChannelSecurityToken::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RegisterServerResponse_Encoding_DefaultBinary => {
                    RegisterServerResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::QueryDataDescription_Encoding_DefaultBinary => {
                    QueryDataDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::QueryFirstRequest_Encoding_DefaultBinary => {
                    QueryFirstRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::OpenSecureChannelRequest_Encoding_DefaultBinary => {
                    OpenSecureChannelRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SessionlessInvokeRequestType_Encoding_DefaultBinary => {
                    SessionlessInvokeRequestType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RegisterNodesResponse_Encoding_DefaultBinary => {
                    RegisterNodesResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadValueId_Encoding_DefaultBinary => {
                    ReadValueId::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SubscriptionAcknowledgement_Encoding_DefaultBinary => {
                    SubscriptionAcknowledgement::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CreateMonitoredItemsResponse_Encoding_DefaultBinary => {
                    CreateMonitoredItemsResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CreateSubscriptionResponse_Encoding_DefaultBinary => {
                    CreateSubscriptionResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SignedSoftwareCertificate_Encoding_DefaultBinary => {
                    SignedSoftwareCertificate::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ProgramDiagnosticDataType_Encoding_DefaultBinary => {
                    ProgramDiagnosticDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::XVType_Encoding_DefaultBinary => {
                    XVType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::FindServersRequest_Encoding_DefaultBinary => {
                    FindServersRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CreateMonitoredItemsRequest_Encoding_DefaultBinary => {
                    CreateMonitoredItemsRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ConfigurationVersionDataType_Encoding_DefaultBinary => {
                    ConfigurationVersionDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AdditionalParametersType_Encoding_DefaultBinary => {
                    AdditionalParametersType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SubscribedDataSetMirrorDataType_Encoding_DefaultBinary => {
                    SubscribedDataSetMirrorDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AddReferencesRequest_Encoding_DefaultBinary => {
                    AddReferencesRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ServerStatusDataType_Encoding_DefaultBinary => {
                    ServerStatusDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryEvent_Encoding_DefaultBinary => {
                    HistoryEvent::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::StructureField_Encoding_DefaultBinary => {
                    StructureField::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SubscriptionDiagnosticsDataType_Encoding_DefaultBinary => {
                    SubscriptionDiagnosticsDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataSetReaderTransportDataType_Encoding_DefaultBinary => {
                    DataSetReaderTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ModifyMonitoredItemsRequest_Encoding_DefaultBinary => {
                    ModifyMonitoredItemsRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::FindServersOnNetworkRequest_Encoding_DefaultBinary => {
                    FindServersOnNetworkRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AddNodesResponse_Encoding_DefaultBinary => {
                    AddNodesResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RedundantServerDataType_Encoding_DefaultBinary => {
                    RedundantServerDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::Frame_Encoding_DefaultBinary => {
                    Frame::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrokerDataSetWriterTransportDataType_Encoding_DefaultBinary => {
                    BrokerDataSetWriterTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteSubscriptionsRequest_Encoding_DefaultBinary => {
                    DeleteSubscriptionsRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoredItemModifyRequest_Encoding_DefaultBinary => {
                    MonitoredItemModifyRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PubSubGroupDataType_Encoding_DefaultBinary => {
                    PubSubGroupDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataTypeDescription_Encoding_DefaultBinary => {
                    DataTypeDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CurrencyUnitType_Encoding_DefaultBinary => {
                    CurrencyUnitType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataTypeSchemaHeader_Encoding_DefaultBinary => {
                    DataTypeSchemaHeader::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CreateSubscriptionRequest_Encoding_DefaultBinary => {
                    CreateSubscriptionRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UserIdentityToken_Encoding_DefaultBinary => {
                    UserIdentityToken::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PublishedDataSetDataType_Encoding_DefaultBinary => {
                    PublishedDataSetDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::JsonDataSetWriterMessageDataType_Encoding_DefaultBinary => {
                    JsonDataSetWriterMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DiscoveryConfiguration_Encoding_DefaultBinary => {
                    DiscoveryConfiguration::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteNodesResponse_Encoding_DefaultBinary => {
                    DeleteNodesResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ViewDescription_Encoding_DefaultBinary => {
                    ViewDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteReferencesRequest_Encoding_DefaultBinary => {
                    DeleteReferencesRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ServerOnNetwork_Encoding_DefaultBinary => {
                    ServerOnNetwork::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::VariableAttributes_Encoding_DefaultBinary => {
                    VariableAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::Argument_Encoding_DefaultBinary => {
                    Argument::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::VariableTypeAttributes_Encoding_DefaultBinary => {
                    VariableTypeAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UserTokenPolicy_Encoding_DefaultBinary => {
                    UserTokenPolicy::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PublishedVariableDataType_Encoding_DefaultBinary => {
                    PublishedVariableDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::WriteRequest_Encoding_DefaultBinary => {
                    WriteRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::IdentityMappingRuleType_Encoding_DefaultBinary => {
                    IdentityMappingRuleType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::StructureDescription_Encoding_DefaultBinary => {
                    StructureDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ModifyMonitoredItemsResponse_Encoding_DefaultBinary => {
                    ModifyMonitoredItemsResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryUpdateResult_Encoding_DefaultBinary => {
                    HistoryUpdateResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AddNodesRequest_Encoding_DefaultBinary => {
                    AddNodesRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::QueryNextRequest_Encoding_DefaultBinary => {
                    QueryNextRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TranslateBrowsePathsToNodeIdsResponse_Encoding_DefaultBinary => {
                    TranslateBrowsePathsToNodeIdsResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CallMethodResult_Encoding_DefaultBinary => {
                    CallMethodResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EventFilterResult_Encoding_DefaultBinary => {
                    EventFilterResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CloseSessionRequest_Encoding_DefaultBinary => {
                    CloseSessionRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::GenericAttributeValue_Encoding_DefaultBinary => {
                    GenericAttributeValue::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowseRequest_Encoding_DefaultBinary => {
                    BrowseRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AddReferencesResponse_Encoding_DefaultBinary => {
                    AddReferencesResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AddNodesResult_Encoding_DefaultBinary => {
                    AddNodesResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteReferencesResponse_Encoding_DefaultBinary => {
                    DeleteReferencesResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AggregateFilter_Encoding_DefaultBinary => {
                    AggregateFilter::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PubSubConfigurationDataType_Encoding_DefaultBinary => {
                    PubSubConfigurationDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::StatusResult_Encoding_DefaultBinary => {
                    StatusResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataChangeFilter_Encoding_DefaultBinary => {
                    DataChangeFilter::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ContentFilter_Encoding_DefaultBinary => {
                    ContentFilter::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UpdateDataDetails_Encoding_DefaultBinary => {
                    UpdateDataDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ViewAttributes_Encoding_DefaultBinary => {
                    ViewAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReaderGroupDataType_Encoding_DefaultBinary => {
                    ReaderGroupDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UserNameIdentityToken_Encoding_DefaultBinary => {
                    UserNameIdentityToken::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataSetMetaDataType_Encoding_DefaultBinary => {
                    DataSetMetaDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CancelResponse_Encoding_DefaultBinary => {
                    CancelResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RegisterServer2Response_Encoding_DefaultBinary => {
                    RegisterServer2Response::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RegisterServerRequest_Encoding_DefaultBinary => {
                    RegisterServerRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CreateSessionRequest_Encoding_DefaultBinary => {
                    CreateSessionRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::JsonDataSetReaderMessageDataType_Encoding_DefaultBinary => {
                    JsonDataSetReaderMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UABinaryFileDataType_Encoding_DefaultBinary => {
                    UABinaryFileDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::FieldMetaData_Encoding_DefaultBinary => {
                    FieldMetaData::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ApplicationDescription_Encoding_DefaultBinary => {
                    ApplicationDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadAnnotationDataDetails_Encoding_DefaultBinary => {
                    ReadAnnotationDataDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataSetReaderMessageDataType_Encoding_DefaultBinary => {
                    DataSetReaderMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteEventDetails_Encoding_DefaultBinary => {
                    DeleteEventDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UnregisterNodesRequest_Encoding_DefaultBinary => {
                    UnregisterNodesRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RelativePathElement_Encoding_DefaultBinary => {
                    RelativePathElement::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SamplingIntervalDiagnosticsDataType_Encoding_DefaultBinary => {
                    SamplingIntervalDiagnosticsDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteNodesRequest_Encoding_DefaultBinary => {
                    DeleteNodesRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::LiteralOperand_Encoding_DefaultBinary => {
                    LiteralOperand::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AggregateFilterResult_Encoding_DefaultBinary => {
                    AggregateFilterResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EnumValueType_Encoding_DefaultBinary => {
                    EnumValueType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NotificationMessage_Encoding_DefaultBinary => {
                    NotificationMessage::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ModifySubscriptionRequest_Encoding_DefaultBinary => {
                    ModifySubscriptionRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RelativePath_Encoding_DefaultBinary => {
                    RelativePath::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NotificationData_Encoding_DefaultBinary => {
                    NotificationData::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AggregateConfiguration_Encoding_DefaultBinary => {
                    AggregateConfiguration::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ElementOperand_Encoding_DefaultBinary => {
                    ElementOperand::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PublishedEventsDataType_Encoding_DefaultBinary => {
                    PublishedEventsDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowseNextResponse_Encoding_DefaultBinary => {
                    BrowseNextResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RegisteredServer_Encoding_DefaultBinary => {
                    RegisteredServer::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteMonitoredItemsRequest_Encoding_DefaultBinary => {
                    DeleteMonitoredItemsRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RationalNumber_Encoding_DefaultBinary => {
                    RationalNumber::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryUpdateRequest_Encoding_DefaultBinary => {
                    HistoryUpdateRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryReadResult_Encoding_DefaultBinary => {
                    HistoryReadResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PubSubConnectionDataType_Encoding_DefaultBinary => {
                    PubSubConnectionDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SimpleTypeDescription_Encoding_DefaultBinary => {
                    SimpleTypeDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TransferSubscriptionsRequest_Encoding_DefaultBinary => {
                    TransferSubscriptionsRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataTypeAttributes_Encoding_DefaultBinary => {
                    DataTypeAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AxisInformation_Encoding_DefaultBinary => {
                    AxisInformation::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::Orientation_Encoding_DefaultBinary => {
                    Orientation::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NetworkGroupDataType_Encoding_DefaultBinary => {
                    NetworkGroupDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SetMonitoringModeResponse_Encoding_DefaultBinary => {
                    SetMonitoringModeResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ParsingResult_Encoding_DefaultBinary => {
                    ParsingResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EUInformation_Encoding_DefaultBinary => {
                    EUInformation::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryData_Encoding_DefaultBinary => {
                    HistoryData::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RepublishRequest_Encoding_DefaultBinary => {
                    RepublishRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CloseSessionResponse_Encoding_DefaultBinary => {
                    CloseSessionResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::OptionSet_Encoding_DefaultBinary => {
                    OptionSet::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrokerDataSetReaderTransportDataType_Encoding_DefaultBinary => {
                    BrokerDataSetReaderTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataChangeNotification_Encoding_DefaultBinary => {
                    DataChangeNotification::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::FindServersOnNetworkResponse_Encoding_DefaultBinary => {
                    FindServersOnNetworkResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EndpointUrlListDataType_Encoding_DefaultBinary => {
                    EndpointUrlListDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteSubscriptionsResponse_Encoding_DefaultBinary => {
                    DeleteSubscriptionsResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ProgramDiagnostic2DataType_Encoding_DefaultBinary => {
                    ProgramDiagnostic2DataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NodeAttributes_Encoding_DefaultBinary => {
                    NodeAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::TrustListDataType_Encoding_DefaultBinary => {
                    TrustListDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DatagramWriterGroupTransportDataType_Encoding_DefaultBinary => {
                    DatagramWriterGroupTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoredItemCreateRequest_Encoding_DefaultBinary => {
                    MonitoredItemCreateRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReaderGroupTransportDataType_Encoding_DefaultBinary => {
                    ReaderGroupTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SubscribedDataSetDataType_Encoding_DefaultBinary => {
                    SubscribedDataSetDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::X509IdentityToken_Encoding_DefaultBinary => {
                    X509IdentityToken::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteAtTimeDetails_Encoding_DefaultBinary => {
                    DeleteAtTimeDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::JsonWriterGroupMessageDataType_Encoding_DefaultBinary => {
                    JsonWriterGroupMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SetMonitoringModeRequest_Encoding_DefaultBinary => {
                    SetMonitoringModeRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PublishedDataSetSourceDataType_Encoding_DefaultBinary => {
                    PublishedDataSetSourceDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryReadDetails_Encoding_DefaultBinary => {
                    HistoryReadDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::WriterGroupMessageDataType_Encoding_DefaultBinary => {
                    WriterGroupMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DatagramConnectionTransportDataType_Encoding_DefaultBinary => {
                    DatagramConnectionTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BuildInfo_Encoding_DefaultBinary => {
                    BuildInfo::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ThreeDOrientation_Encoding_DefaultBinary => {
                    ThreeDOrientation::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::QueryDataSet_Encoding_DefaultBinary => {
                    QueryDataSet::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::WriterGroupTransportDataType_Encoding_DefaultBinary => {
                    WriterGroupTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowseNextRequest_Encoding_DefaultBinary => {
                    BrowseNextRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowsePathTarget_Encoding_DefaultBinary => {
                    BrowsePathTarget::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DecimalDataType_Encoding_DefaultBinary => {
                    DecimalDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EndpointConfiguration_Encoding_DefaultBinary => {
                    EndpointConfiguration::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PublishRequest_Encoding_DefaultBinary => {
                    PublishRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowseResponse_Encoding_DefaultBinary => {
                    BrowseResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EventFilter_Encoding_DefaultBinary => {
                    EventFilter::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryReadValueId_Encoding_DefaultBinary => {
                    HistoryReadValueId::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MdnsDiscoveryConfiguration_Encoding_DefaultBinary => {
                    MdnsDiscoveryConfiguration::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UpdateStructureDataDetails_Encoding_DefaultBinary => {
                    UpdateStructureDataDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::PublishResponse_Encoding_DefaultBinary => {
                    PublishResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DeleteNodesItem_Encoding_DefaultBinary => {
                    DeleteNodesItem::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SessionlessInvokeResponseType_Encoding_DefaultBinary => {
                    SessionlessInvokeResponseType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ModifySubscriptionResponse_Encoding_DefaultBinary => {
                    ModifySubscriptionResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NodeTypeDescription_Encoding_DefaultBinary => {
                    NodeTypeDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryReadResponse_Encoding_DefaultBinary => {
                    HistoryReadResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ModificationInfo_Encoding_DefaultBinary => {
                    ModificationInfo::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SessionDiagnosticsDataType_Encoding_DefaultBinary => {
                    SessionDiagnosticsDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SessionSecurityDiagnosticsDataType_Encoding_DefaultBinary => {
                    SessionSecurityDiagnosticsDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReaderGroupMessageDataType_Encoding_DefaultBinary => {
                    ReaderGroupMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoringFilterResult_Encoding_DefaultBinary => {
                    MonitoringFilterResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryUpdateResponse_Encoding_DefaultBinary => {
                    HistoryUpdateResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AttributeOperand_Encoding_DefaultBinary => {
                    AttributeOperand::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CreateSessionResponse_Encoding_DefaultBinary => {
                    CreateSessionResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoredItemModifyResult_Encoding_DefaultBinary => {
                    MonitoredItemModifyResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::GetEndpointsRequest_Encoding_DefaultBinary => {
                    GetEndpointsRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::WriteResponse_Encoding_DefaultBinary => {
                    WriteResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ServiceCounterDataType_Encoding_DefaultBinary => {
                    ServiceCounterDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EndpointDescription_Encoding_DefaultBinary => {
                    EndpointDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadRawModifiedDetails_Encoding_DefaultBinary => {
                    ReadRawModifiedDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::DataSetReaderDataType_Encoding_DefaultBinary => {
                    DataSetReaderDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ThreeDFrame_Encoding_DefaultBinary => {
                    ThreeDFrame::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NodeReference_Encoding_DefaultBinary => {
                    NodeReference::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ThreeDVector_Encoding_DefaultBinary => {
                    ThreeDVector::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ActivateSessionResponse_Encoding_DefaultBinary => {
                    ActivateSessionResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadResponse_Encoding_DefaultBinary => {
                    ReadResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryReadRequest_Encoding_DefaultBinary => {
                    HistoryReadRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoredItemCreateResult_Encoding_DefaultBinary => {
                    MonitoredItemCreateResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ObjectTypeAttributes_Encoding_DefaultBinary => {
                    ObjectTypeAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::StatusChangeNotification_Encoding_DefaultBinary => {
                    StatusChangeNotification::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::NetworkAddressDataType_Encoding_DefaultBinary => {
                    NetworkAddressDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EnumField_Encoding_DefaultBinary => {
                    EnumField::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UnregisterNodesResponse_Encoding_DefaultBinary => {
                    UnregisterNodesResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReferenceDescription_Encoding_DefaultBinary => {
                    ReferenceDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoringFilter_Encoding_DefaultBinary => {
                    MonitoringFilter::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::GenericAttributes_Encoding_DefaultBinary => {
                    GenericAttributes::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoredItemNotification_Encoding_DefaultBinary => {
                    MonitoredItemNotification::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::KeyValuePair_Encoding_DefaultBinary => {
                    KeyValuePair::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadAtTimeDetails_Encoding_DefaultBinary => {
                    ReadAtTimeDetails::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ComplexNumberType_Encoding_DefaultBinary => {
                    ComplexNumberType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowseResult_Encoding_DefaultBinary => {
                    BrowseResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ReadRequest_Encoding_DefaultBinary => {
                    ReadRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowseDescription_Encoding_DefaultBinary => {
                    BrowseDescription::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::FindServersResponse_Encoding_DefaultBinary => {
                    FindServersResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::HistoryEventFieldList_Encoding_DefaultBinary => {
                    HistoryEventFieldList::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EventNotificationList_Encoding_DefaultBinary => {
                    EventNotificationList::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::UadpWriterGroupMessageDataType_Encoding_DefaultBinary => {
                    UadpWriterGroupMessageDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::BrowsePathResult_Encoding_DefaultBinary => {
                    BrowsePathResult::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::Annotation_Encoding_DefaultBinary => {
                    Annotation::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CallResponse_Encoding_DefaultBinary => {
                    CallResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::EndpointType_Encoding_DefaultBinary => {
                    EndpointType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AliasNameDataType_Encoding_DefaultBinary => {
                    AliasNameDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::AddReferencesItem_Encoding_DefaultBinary => {
                    AddReferencesItem::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::FilterOperand_Encoding_DefaultBinary => {
                    FilterOperand::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::CartesianCoordinates_Encoding_DefaultBinary => {
                    CartesianCoordinates::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ServiceFault_Encoding_DefaultBinary => {
                    ServiceFault::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::MonitoringParameters_Encoding_DefaultBinary => {
                    MonitoringParameters::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ThreeDCartesianCoordinates_Encoding_DefaultBinary => {
                    ThreeDCartesianCoordinates::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ConnectionTransportDataType_Encoding_DefaultBinary => {
                    ConnectionTransportDataType::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::ActivateSessionRequest_Encoding_DefaultBinary => {
                    ActivateSessionRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RegisterNodesRequest_Encoding_DefaultBinary => {
                    RegisterNodesRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::RegisterServer2Request_Encoding_DefaultBinary => {
                    RegisterServer2Request::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::QueryFirstResponse_Encoding_DefaultBinary => {
                    QueryFirstResponse::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                opcua::types::ObjectId::SetTriggeringRequest_Encoding_DefaultBinary => {
                    SetTriggeringRequest::from_xml(body, ctx)
                        .map(|v| opcua::types::ExtensionObject::from_message(&v))
                }
                _ => return None,
            },
        )
    }
}
