name: Run and verify clippy
'on':
  workflow_call: null
jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run clippy
        run: cargo clippy -- -D warnings
