name: CI verify cleanly generated code
'on':
  workflow_call: null
jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Run code gen
        run: cargo run --bin opcua-codegen code_gen_config.yml
      - name: Format generated code
        run: rustfmt opcua-types/src/service_types/mod.rs
      - name: Format address space
        run: rustfmt opcua-core-namespace/src/generated/mod.rs
      - name: Verify generated code matches committed code
        run: git status --porcelain

