name: OPC UA for Rust

on:
  push:
    branches: [ master, rewrite-master ]
  pull_request:
    branches: [ master, rewrite-master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Provision toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Build
        run: cargo check
      - name: Run tests
        run: cargo test --verbose

  test-external-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build .NET
        run: dotnet build
      - name: Run tests against external server
        run: cargo run --bin external-tests

  code-coverage:
    uses: ./.github/workflows/ci_code_coverage.yml

  clippy:
    uses: ./.github/workflows/ci_clippy.yml

  verify-clean-codegen:
    uses: ./.github/workflows/ci_verify_clean_codegen.yml

