name: OPC UA for Rust

on:
  push:
    branches: [ master, rewrite-master ]
  pull_request:
    branches: [ master, rewrite-master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Provision toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose

  # build-windows:
  #   strategy:
  #     matrix:
  #       toolchain:
  #         - stable
  #         - beta
  #   runs-on: windows-latest
  #   env:
  #     VCPKGRS_DYNAMIC: 1
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Provision toolchain
  #       run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
  #     - name: Build
  #       run: cargo build
  #     - name: Run tests
  #       run: cargo test --verbose

  code-coverage:
    uses: ./.github/workflows/ci_code_coverage.yml

  clippy:
    uses: ./.github/workflows/ci_clippy.yml

  verify-clean-node-ids:
    uses: ./.github/workflows/ci_verify_clean_node_ids.yml

  verify-clean-supported-message:
    uses: ./.github/workflows/ci_verify_clean_supported_message.yml

  verify-clean-codegen:
    uses: ./.github/workflows/ci_verify_clean_codegen.yml

  verify-code-formatting:
    uses: ./.github/workflows/ci_format_code.yml
